#include <stdio.h>
#include <stdlib.h>
#include <time.h>


void carteChance(int argentJ, int positionJ, int nbJoueurs){

       int numeroCarteChance = 0;
       numeroCarteChance =1+rand()%16;

       if (numeroCarteChance == 1){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *      MAMIE EST MORTE...    *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *        VOUS TOUCHEZ        *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *    150 euros D'HERITAGE    *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ=argentJ+150;
       }
       if (numeroCarteChance == 2){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *         RENDEZ-VOUS        *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *  BOULEVARD DES PAILLETTES  *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                * POUR UN VERRE EN TERRASSE !*\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
           // positionJ =  ;// Case Boulevard des Paillettes
       }
       if (numeroCarteChance == 3){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *     BON ANNIVERSAIRE !!!   *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *     CHAQUE JOUEUR DOIT     *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *    VOUS DONNER 20 euros    *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ = argentJ+((nbJoueurs-1)*20);
            //Faire perdre 20 euros aux autres joueurs !!
       }
       if (numeroCarteChance == 4){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *  VOUS TOUCHEZ VOTRE BONUS  *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *   DE L'ANNEE D'UNE VALEUR  *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *        DE 200 euros !      *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ=argentJ+200;
       }
       if (numeroCarteChance == 5){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *   VOUS PARTEZ EN VOYAGE !  *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *      RENDEZ-VOUS DANS      *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *   LA GARE LA PLUS PROCHE   *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
           /* if (1 <=positionJ<= 7){
                positionJ = gare1;   //case 5
            }
            if (8 <= positionJ <= 14){
                positionJ = gare2;  // case 11
            }
            if (15 <= positionJ <= 21){
                positionJ = gare3;  //case19
            }
            if (22 <= positionJ <= 28){
                positionJ = gare4;  //case 26
            }*/
       }

       if (numeroCarteChance == 6){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *      ALCOOL AU VOLANT      *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *       LE SOIR DU 31 !      *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *    SOUDOYEZ LE POLICIER    *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *      DE 40 euros POUR      *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *    GARDER VOTRE PERMIS !   *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ=argentJ-40;
       }
        if (numeroCarteChance == 7){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *  FACTURE EDF DE DECEMBRE : *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *         60 euros !!!       *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *    FALLAIT PAS INSTALLER   *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *    AUTANT DE DECORATIONS   *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *          DE NOEL!          *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                ******************************\n");
            argentJ = argentJ - 60;
       }
       if (numeroCarteChance == 8){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *BONNE RESOLUTION DE L'ANNEE!*\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                * VOUS PRENEZ UN ABONNEMENT  *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *     A LA SALLE DE SPORT    *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *     ET PAYEZ 75 euros...   *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ=argentJ-75;
       }
       if (numeroCarteChance == 9){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *  VOUS VENEZ D'ETRE DEBITE  *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *    DES 80 euros DEPENSES   *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                * EN BOITE SAMEDI DERNIER... *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *          OUI OUI...        *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *      C'ETAIT BIEN VOUS     *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ=argentJ-80;
       }
       if (numeroCarteChance == 10){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *    VOS COMPTES OFFSHORE    *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *     ONT ETE DECOUVERTS,    *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *  TROP TARD POUR S'ENFUIR,  *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *    DIRECTION LA PRISON !   *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
           // positionJ = prison ;   // case 22
       }
       if (numeroCarteChance == 11){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *       VOUS ETES LIBERE     *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *          DE PRISON         *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *    POUR BONNE CONDUITE !   *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            // a garder et a utiliserulterieurement
       }
       if (numeroCarteChance == 12){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("               *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *    VOTRE ENFANT RECLAME    *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *   UNE CONSOLE POUR NOEL :  *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *      DEPENSEZ 30 euros     *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *   AVANT QU'IL NE SE METTE  *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *         A CRIER !!!        *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ=argentJ-30;
       }
       if (numeroCarteChance == 13){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *    VOUS AVEZ FAIT TOMBER   *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *    VOTRE PORTE-FEUILLE !   *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *      RECULEZ DE 3 CASES    *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *      POUR LE RETROUVER !   *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            positionJ= positionJ -3;
       }
       if (numeroCarteChance == 14){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *   VOUS AVEZ FAIT BEAUCOUP  *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *   D'HEURES SUP CE MOIS-CI  *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *      TOUCHEZ UE PRIME      *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *         DE 80 euros        *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ=argentJ+80;
        }
       if (numeroCarteChance == 15){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *  C A R T E   C H A N C E   *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *       PAPI EST TOMBE       *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *     DANS LES ESCALIERS !   *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *  FRAIS D'HOSPITALISATION : *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *          65 euros...       *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ = argentJ - 65;
       }
       if (numeroCarteChance == 16){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *   C A R T E   C H A N C E  *\n");
            gotoligcol(28,100);
            printf("                *                            *\n");
            gotoligcol(29,100);
            printf("                ******************************\n");
            gotoligcol(30,100);
            printf("                *                            *\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *             HOP !          *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *   VOUS TROUVEZ UN BILLET   *\n");
            gotoligcol(35,100);
            printf("                *         DE 50 EUROS        *\n");
            gotoligcol(36,100);
            printf("                *          PAR TERRE :       *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *       VOUS LE GARDEZ,      *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *      BIEN EVIDEMMENT...    *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            argentJ = argentJ + 50;
       }

        return 0;
}



void carteCommunaute(int argentJ, int positionJ, int nbJoueurs){

       int numeroCarteCommunaute = 0; // Variable cartes communaute
       numeroCarteCommunaute =1+rand()%16; // Tire une carte au hazard

       if (numeroCarteCommunaute == 1){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *     VOUS TOUCHEZ ENFIN     *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *       VOS DIVIDENDES       *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *        DE 100 euros !      *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ + 100 ;
       }
       if (numeroCarteCommunaute == 2){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *    EVITEZ DE RATER VOTRE   *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *   TRAIN EN VOUS DEPLACANT  *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                * VERS LA GARE LA PLUS PROCHE*\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            if (1 <=positionJ<= 7){
                positionJ = 5;   // Gare de la sante
            }
            if (8 <= positionJ <= 14){
                positionJ = 11;  // Gare de l'amour
            }
            if (15 <= positionJ <= 21){
                positionJ = 19;  // Gare de la fortune
            }
            if (22 <= positionJ <= 28){
                positionJ = 26;  // Gare de la chance
            }
       }
       if (numeroCarteCommunaute == 3){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *       C'EST NOEL !!!       *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *     RECEVEZ UN CHEQUE      *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *    DE MAMIE DE 80 euros    *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *     AH ! ET UNE LETTRE.    *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ + 80 ;
       }
       if (numeroCarteCommunaute == 4){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *  COUP DUR : IL EST TEMPS   *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *  DE PAYER LES IMPOTS, VOUS *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *       PERDEZ 120 euros     *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ - 120;
       }
       if (numeroCarteCommunaute == 5){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *  VOUS ETES EN RETARD POUR  *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *    VOTRE DATE AU PASSAGE   *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *     DU BISOUS-DE-MINUIT,   *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *    RENDEZ-VOUS Y AU PLUS   *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *     VITE POUR AVOIR UNE    *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *   UNE CHANCE DE CONCLURE   *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            positionJ = 10; // Case passage du bisous-de-minuit
       }

       if (numeroCarteCommunaute == 6){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *     VOLER DES BONBONS      *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *   DANS UNE BOULANGERIE...  *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *         SERIEUX ?          *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *    DIRECTION LA PRISON !   *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                ******************************\n");
            positionJ = 22 ;   // case prison
       }
        if (numeroCarteCommunaute == 7){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *           BIEN VU !        *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *       VOUS AVEZ GAGNE      *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *        A LA LOTTERIE,      *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *    RECEVEZ UN CHEQUE DE    *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *         350 euros !        *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ + 350 ;
       }
       if (numeroCarteCommunaute == 8){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *     LA FASHIONISTA QUE     *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *    VOUS ETES S'EST FAIT    *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *     PLAISIR CE MOIS-CI,    *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *   VOTRE COMPTE EN BANQUE   *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *  APPRECIE MOINS EN PERDANT *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *          115 EUROS         *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ - 115 ;
       }
       if (numeroCarteCommunaute == 9){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *      VOS CONTACTS ONT      *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *     JOUES ET VOUS ETES     *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *     LIBERES DE PRISON !    *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            // A utiliser ulterieurement
       }
       if (numeroCarteCommunaute == 10){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *           VITE !           *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                * RENDEZ-VOUS RUE DU DECOMPTE*\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *      POUR LE REVEILLON     *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            positionJ = 27 ;
       }
       if (numeroCarteCommunaute == 11){
           gotoligcol(25,100);
            printf("\n              ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *     RADIN QUE VOUS ETES,   *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *      VOUS VOUS FAITES      *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *   REMBOURSER VOTRE TENUE   *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *           DU 31,           *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *  VOUS RECUPEREZ 25 euros ! *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ + 25 ;
       }
       if (numeroCarteCommunaute == 12){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *    VOTRE PARTICIPATION     *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *     A UNE TELEREALITE      *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *  VOUS RAPPORTE 200 euros ! *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ + 200 ;
       }
       if (numeroCarteCommunaute == 13){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *   A FAIRE L'INFLUENCEUR    *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *   AU BORD DE LA PISCINE,   *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *    VOTRE TELEPHONE FINI    *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *          A L'EAU !         *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *    PAYEZ 120 EUROS POUR    *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *         LE REMPLACER       *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ - 120 ;
       }
       if (numeroCarteCommunaute == 14){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                *    TESTEZ VOS NOUVELLES    *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *                            *\n");
            gotoligcol(37,100);
            printf("                *     BASKETS ET AVANCEZ     *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *        DE 5 CASES !        *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            positionJ = positionJ + 5 ;
        }
       if (numeroCarteCommunaute == 15){
           gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *    ACCIDENT DE VOITURE !   *\n");
            gotoligcol(34,100);
            printf("                *                            *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *       PAYEZ 50 euros       *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *                            *\n");
            gotoligcol(39,100);
            printf("                *       DE REPARATION,       *\n");
            gotoligcol(40,100);
            printf("                *                            *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                * ON FREINE DEVANT UN ARBRE..*\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ - 50 ;
       }
       if (numeroCarteCommunaute == 16){
            gotoligcol(25,100);
            printf("                ******************************\n");
            gotoligcol(26,100);
            printf("                *                            *\n");
            gotoligcol(27,100);
            printf("                *       C A R T E   D E      *\n");
            gotoligcol(28,100);
            printf("                *      C O M M U N A U T E   *\n");
            gotoligcol(29,100);
            printf("                *                            *\n");
            gotoligcol(30,100);
            printf("                ******************************\n");
            gotoligcol(31,100);
            printf("                *                            *\n");
            gotoligcol(32,100);
            printf("                *                            *\n");
            gotoligcol(33,100);
            printf("                *                            *\n");
            gotoligcol(34,100);
            printf("                * VOUS CASSEZ VOTRE TIRELIRE *\n");
            gotoligcol(35,100);
            printf("                *                            *\n");
            gotoligcol(36,100);
            printf("                *     ET TROUVEZ 10 euros,   *\n");
            gotoligcol(37,100);
            printf("                *                            *\n");
            gotoligcol(38,100);
            printf("                *       ON OUBLIE PAS        *\n");
            gotoligcol(39,100);
            printf("                *                            *\n");
            gotoligcol(40,100);
            printf("                *   LES PETITES ECONOMIES !  *\n");
            gotoligcol(41,100);
            printf("                *                            *\n");
            gotoligcol(42,100);
            printf("                *                            *\n");
            gotoligcol(43,100);
            printf("                *                            *\n");
            gotoligcol(44,100);
            printf("                *                            *\n");
            gotoligcol(45,100);
            printf("                ******************************\n");
            argentJ = argentJ + 10;
       }

       return 0;
}
